## PRODUCTION ##
server:
  port: 8080

spring:
  datasource:
    url: jdbc:mariadb://${DB_HOST:127.0.0.1}:${DB_PORT:3306}/${DB_NAME:budget}?useUnicode=true&characterEncoding=utf8&sessionVariables=sql_mode='STRICT_ALL_TABLES'
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.dialect: org.hibernate.dialect.MariaDBDialect
      hibernate.format_sql: true
    open-in-view: false
  sql:
    init:
      mode: never
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 300000
      connection-timeout: 30000
      max-lifetime: 1800000